// API接口地址配置
// 通过环境变量读取，需在 .env 文件中配置
// NEXT_PUBLIC_API_BASE_URL: API 基础地址
// NEXT_PUBLIC_NEXT_API_BASE_URL: Next.js API 地址
// NEXT_PUBLIC_PICTURE_BASE_URL: 图片服务基础地址
export const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL || 'http://localhost:8090/api'
export const NEXT_API_BASE_URL = process.env.NEXT_PUBLIC_NEXT_API_BASE_URL || 'http://localhost:8090/next-api'
export const PICTURE_BASE_URL = process.env.NEXT_PUBLIC_PICTURE_BASE_URL || 'https://hanphone.top'

// 通过修改ENDPOINTS可以修改API接口路径
export const ENDPOINTS = {
  LOGIN: `${API_BASE_URL}/login`,
  REGISTER: `${API_BASE_URL}/register`,
  SEARCH: `${API_BASE_URL}/search`,
  BLOG: `${API_BASE_URL}/blog`,
  BLOGS: `${API_BASE_URL}/blogs`,
  PROJECTS: `${API_BASE_URL}/projects`,
  PROJECT_DETAIL: (id: number) => `${API_BASE_URL}/projects/${id}`,
  PROJECT_SEARCH: `${API_BASE_URL}/projects/search`,
  RECOMMEND_PROJECT_LIST: `${API_BASE_URL}/getRecommendProjectList`,
  FRIENDLINKS: `${API_BASE_URL}/friendLinks`,
  FRIENDLINKS_APPLY: `${API_BASE_URL}/friendLinks/apply`,
  RECOMMEND_BLOG_LIST: `${API_BASE_URL}/getRecommendBlogList`,
  RECOMMEND_ESSAY_LIST: `${API_BASE_URL}/getRecommendEssayList`,
  SITE_STATS: `${API_BASE_URL}/site-stats`,
  TYPE_LIST: `${API_BASE_URL}/getTypeList`,
  TAG_LIST: `${API_BASE_URL}/getTagList`,
  FULL_TYPE_LIST: `${API_BASE_URL}/getFullTypeList`,
  FULL_TAG_LIST: `${API_BASE_URL}/getFullTagList`,
  TYPE_BLOGS: (id: number) => `${API_BASE_URL}/types/${id}`,
  TAG_BLOGS: (id: number) => `${API_BASE_URL}/tags/${id}`,
  MESSAGES: `${API_BASE_URL}/messages`,
  ESSAYS: `${API_BASE_URL}/essays`,
  ESSAY_DETAIL: (id: number) => `${API_BASE_URL}/essays/${id}`,
  ESSAY_COMMENTS: (id: number) => `${API_BASE_URL}/essays/${id}/comments`,
  ESSAY_SEARCH: `${API_BASE_URL}/essays/search`,
  RECOMMEND_BLOGS: `${API_BASE_URL}/getRecommendBlogList`,
  RANDOM_BLOGS: `${API_BASE_URL}/blogs/random`,
  ARCHIVE_BLOGS: `${API_BASE_URL}/archiveBlog`,
  BLOG_PREV: (id: number) => `${API_BASE_URL}/blog/${id}/prev`,
  BLOG_NEXT: (id: number) => `${API_BASE_URL}/blog/${id}/next`,
  UPLOAD_BLOG_IMAGE: `${API_BASE_URL}/upload/blogs`,
  COMMENTS: `${API_BASE_URL}/comments`,
  GET_VISIT_COUNT: `${API_BASE_URL}/visit-count`,
  FILE: {
    UPLOAD: `${PICTURE_BASE_URL}/upload/`,
    UPLOAD_BATCH: `${PICTURE_BASE_URL}/upload/batch`,
    DELETE: `${PICTURE_BASE_URL}/delete/`,
    GET_FILE: `${PICTURE_BASE_URL}/file/`,
    GET_FILES: `${PICTURE_BASE_URL}/files/`,
    DIRECTORY: `${PICTURE_BASE_URL}/directory/`,
    AVATAR_UPLOAD: `${PICTURE_BASE_URL}/upload/avatar`
  },
  CHAT: {
    POST_PRIVATE_MESSAGES: `${NEXT_API_BASE_URL}/postPrivateMessages`,
    GET_PRIVATE_MESSAGES: `${NEXT_API_BASE_URL}/getPrivateMessages`,
    GETUSER: `${NEXT_API_BASE_URL}/user`
  },
  DOCS: `${API_BASE_URL}/docs`,
  DOC_DETAIL: (docId: string) => `${API_BASE_URL}/docs/${docId}`,
  DOC_VIEW: (docId: string) => `${API_BASE_URL}/docs/${docId}/view`,
  DOCS_HOT: `${API_BASE_URL}/docs/hot`,
  DOCS_RECOMMENDED: `${API_BASE_URL}/docs/recommended`,
  OAUTH: {
    AUTHORIZE: (provider: string) => `${API_BASE_URL}/oauth/${provider}/authorize`,
  },
  USER: {
    PERSONINFOS: `${API_BASE_URL}/personInfos`,
    SET_AVATAR: `${API_BASE_URL}/admin/setAvatar`,
    SEND_CAPTCHA: `${API_BASE_URL}/user/sendCaptcha`,
    FORGET_PASSWORD: `${API_BASE_URL}/user/resetPassword`,
    RESET_PASSWORD: `${API_BASE_URL}/admin/user/resetPassword`,
    UPDATE_USER_INFO: `${API_BASE_URL}/user/current/update`,
    BIND_OAUTH: `${API_BASE_URL}/user/bind/oauth`,
    UNBIND_OAUTH: `${API_BASE_URL}/user/unbind/oauth`,
  },
  ADMIN: {
    USERS: `${API_BASE_URL}/admin/users`,
    PERSONINFOS: `${API_BASE_URL}/admin/personInfos`,
    PERSONINFO: `${API_BASE_URL}/admin/personInfo`,
    GETBLOGCOUNT: `${API_BASE_URL}/admin/getBlogCount`,
    GET_VISIT_COUNT_BY_MONTH: `${API_BASE_URL}/admin/getVisitCountByMonth`,
    GETVIEWCOUNT: `${API_BASE_URL}/admin/getViewCount`,
    GETAPPRECIATECOUNT: `${API_BASE_URL}/admin/getAppreciateCount`,
    GETCOMMENTCOUNT: `${API_BASE_URL}/admin/getCommentCount`,
    GETBLOGLIKES: `${API_BASE_URL}/admin/getBlogLikes`,
    BLOG_RECOMMEND: `${API_BASE_URL}/admin/blogs/recommend`,
    ESSAY_RECOMMEND: `${API_BASE_URL}/admin/essays/recommend`,
    ESSAY_PUBLISHED: `${API_BASE_URL}/admin/essays/published`,
    PROJECT_RECOMMEND: `${API_BASE_URL}/admin/projects/recommend`,
    PROJECT_PUBLISHED: `${API_BASE_URL}/admin/projects/published`,
    FRIENDLINK_RECOMMEND: `${API_BASE_URL}/admin/friendLinks/recommend`,
    FRIENDLINK_PUBLISHED: `${API_BASE_URL}/admin/friendLinks/published`,
    FRIENDLINK_PARSE: `${API_BASE_URL}/admin/friendLinks/parse`,
    LIKES_BY_MONTH: `${API_BASE_URL}/admin/getLikesByMonth`,
    VIEWS_BY_MONTH: `${API_BASE_URL}/admin/getViewCountByMonth`,
    BLOGS_BY_MONTH: `${API_BASE_URL}/admin/getBlogCountByMonth`,
    APPRECIATES_BY_MONTH: `${API_BASE_URL}/admin/getAppreciateCountByMonth`,
    COMMENTS_BY_MONTH: `${API_BASE_URL}/admin/getCommentCountByMonth`,
    FULL_TAG_LIST: `${API_BASE_URL}/admin/getFullTagList`,
    GET_FULL_TAG_LIST_AND_BLOG_NUMBER: `${API_BASE_URL}/admin/getFullTagListAndBlogNumber`,
    FULL_TYPE_LIST: `${API_BASE_URL}/admin/getFullTypeList`,
    USER_AREA_LIST: `${API_BASE_URL}/admin/getUserAreaList`,
    COMMMENT_LIST: `${API_BASE_URL}/admin/getCommentList`,
    DOCS: `${API_BASE_URL}/admin/docs`,
    DOC: `${API_BASE_URL}/admin/doc`,
    DOC_RECOMMEND: `${API_BASE_URL}/admin/docs/recommend`,
    DOC_PUBLISHED: `${API_BASE_URL}/admin/docs/published`,
    BLOG_LIST: `${API_BASE_URL}/admin/getBlogList`,
    BLOGS: `${API_BASE_URL}/admin/blogs`,
    USER: `${API_BASE_URL}/admin/user`,
    TAGS: `${API_BASE_URL}/admin/tags`,
    TYPES: `${API_BASE_URL}/admin/types`,
    PROJECT: `${API_BASE_URL}/admin/project`,
    PROJECTS: `${API_BASE_URL}/admin/projects`,
    FRIENDLINK: `${API_BASE_URL}/admin/friendLink`,
    FRIENDLINKS: `${API_BASE_URL}/admin/friendLinks`,
    ESSAY: `${API_BASE_URL}/admin/essay`,
    ESSAYS: `${API_BASE_URL}/admin/essays`,
    DEAL_DELETED_TAG: `${API_BASE_URL}/admin/dealDeletedTag`,
    MCP_KEYS: `${API_BASE_URL}/admin/mcp-keys`
  }
}
